from __future__ import annotations

__all__ = ["BlockDiagConfig", "SparsityPattern"]

import weakref
from dataclasses import dataclass
from functools import cached_property
from typing import Sequence

import torch
from jaxtyping import Bool, Int64, Integer
from torch import Tensor

from ...utils.parsing import parse_to
from ._index import (
    coalesced_coo_to_compressed_idx,
    coalesced_coo_to_csc_row_idx,
    coalesced_coo_to_csr_col_idx,
    get_csc_to_coo_map,
)


def _validate_coo_idx_shape(coo_idx: Int64[Tensor, "sp nz"], shape: torch.Size):
    """
    Validate the shape of a COO index.

    This function checks the following two properties of the COO index tensor:
    * The COO index tensor has shape (2, nz) or (3, nz).
    * If the COO index tensor has a batch dimension, then the number of nonzero
      element per batch must be equal.

    Note that, the second condition of equal nnz per batch element is in general
    not required by PyTorch for sparse tensors in the COO format, but it is required
    for conversion to CSC and CSR formats.
    """
    match len(shape):
        case 1:
            raise ValueError(
                "The 'idx_coo' tensor must have at least two sparse dimensions."
            )

        case 2:
            if coo_idx.size(0) != 2:
                raise ValueError(
                    "For a 2D sparse coo tensor, 'idx_coo' must be of shape (2, nnz)."
                )

        case 3:
            if coo_idx.size(0) != 3:
                raise ValueError(
                    "For a sparse coo tensor with a batch dimension, 'idx_coo' "
                    + "must be of shape (3, nnz)."
                )

            nnz = coo_idx.size(-1)
            n_batch = shape[0]
            batch_idx = coo_idx[0]

            # For batched sparse tensors, enforce the condition that the tensor
            # has equal nnz along the batch dimension, which is required for
            # conversion to sparse csr format.

            # If the input tensor has equal nnz along the batch dimension, then
            # the nnz per tensor in the batch is given by nnz // batch.
            if nnz % n_batch != 0:
                raise ValueError(
                    f"Total nnz ({nnz}) is not divisible by batch size ({n_batch})."
                )

            nnz_per_batch = nnz // n_batch

            # It is possible for a tensor to have non-equal nnz along the batch
            # dimension but still satisfies nnz % batch = 0 (e.g., if the first
            # tensor has 6 nnz, while the second has 2). This second check rules
            # out this possibility.
            if batch_idx is not None:
                batch_counts = torch.bincount(batch_idx, minlength=n_batch)
                if not (batch_counts == nnz_per_batch).all():
                    raise ValueError(
                        "The equal nnz per batch item condition is not met."
                    )

        case _:
            raise NotImplementedError(
                "More than one batch dimensions is not supported."
            )


def check_pattern_equality(
    self_pattern: SparsityPattern, other_pattern: SparsityPattern, msg: str
):
    """
    Check whether two SparsityPattern objects are equivalent.

    Two sparsity patterns/topologies are equivalent if they satisfy one of the
    following conditions:
    * The two sparsity patterns point to the same Python object, or
    * The two sparsity patterns have the same shape and COO indices.
    """
    if self_pattern is other_pattern:
        pass

    elif self_pattern.shape == other_pattern.shape and torch.equal(
        self_pattern.idx_coo, other_pattern.idx_coo
    ):
        pass

    else:
        raise ValueError(msg)


@dataclass(frozen=True)
class BlockDiagConfig:
    """
    Block-diagonal sparse tensor pattern.

    This immutable dataclass encodes information on the structure of a block-diagonal
    `SparseDecoupledTensor`. It is generated by `pack_block_diag()` during block
    diagonal construction and consumed by `unpack_block_diag()` to split a
    block-diagonal tensor into its constituent tensors.

    Parameters
    ----------
    batch_perm : [nz,]
        An int64 tensor that represents the permutation required to sort the
        row-major concatenated COO index tensor to a batch-major tensor. If the
        tensor has no batch dimension, this tensor contains the identity permutation.
    nnzs : [b,]
        The number of nonzero elements per block.
    pattern_shapes : [b,]
        The shape of block.

    Attributes
    ----------
    batch_perm_inv : [nz,]
        The inverse of the batch_perm permutation.

    Notes
    -----
    Block-diagonal `SparseDecoupledTensor`s derived from block-diagonal mesh
    batching do not have `BlockDiagConfig`s. To unpack such tensors, see the
    `unpack_by_ptrs()` method of `SparseDecoupledTensor`.
    """

    batch_perm: Int64[Tensor, " nz"]
    nnzs: list[int]
    pattern_shapes: list[torch.Size]

    def to(self, *args, **kwargs) -> BlockDiagConfig:
        """
        Call to() on attached tensor batch_perm.

        Note that dtype conversions are ignored.
        """
        device, dtype, copy_flag, non_blocking, memory_format = parse_to(
            *args, **kwargs
        )
        new_batch_perm = self.batch_perm.to(
            device=device,
            copy=copy_flag,
            non_blocking=non_blocking,
            memory_format=memory_format,
        )
        return BlockDiagConfig(new_batch_perm, self.nnzs, self.pattern_shapes)

    @property
    def batch_perm_inv(self) -> Int64[Tensor, " nz"]:
        """
        The inverse of the batch_perm permutation.

        Note that this scattering approach is strictly better than
        `torch.argsort(batch_perm)` for a permutation.
        """
        nnz = self.batch_perm.size(0)

        inv = torch.empty_like(self.batch_perm)
        inv[self.batch_perm] = torch.arange(
            nnz, dtype=self.batch_perm.dtype, device=self.batch_perm.device
        )

        return inv


# TODO: check csc/csr index tensor dtype agreement with idx_coo.
# TODO: check index tensor contiguous memory.
# Use eq=False so that hashing is ID-based.
@dataclass(frozen=True, eq=False)
class SparsityPattern:
    """
    `SparseDecoupledTensor` sparsity pattern/topology.

    This immutable dataclass stores the sparsity pattern of a `SparseDecoupledTensor`
    in the form of its COO index tensor and provides methods for conversion to
    CSR and CSC representations. In addition, the class contains methods that
    facilitate the (dis)assembling of block-structured matrices and taking
    submatrices.

    This class supports sparse tensors with at most one leading batch dimension.

    Parameters
    ----------
    _idx_coo : [sp, nz]
        The COO index tensor. This tensor is assumed to be coalesced (which is
        not checked). If the tensor has a batch dimension, sp = 3; otherwise
        sp = 2. This class will always create and store a contiguous copy of the
        input COO index tensor to enforce ownership of the sparsity data.
    shape
        The shape of the sparse tensor. If the tensor has a batch dimension,
        its shape should be (batch, row, col); otherwise it should be (row, col).
        Note that the SparseDecoupledTensor supports trailing dense dimensions,
        but such dimensions are not reflected in the shape of the `SparsityPattern`.
    block_diag_config
        A BlockDiagConfig object that describes the block-diagonal structure of
        the tensor; relevant for `pack_block_diag()` and `unpack_block_diag()`.

    Attributes
    ----------
    idx_coo : [sp, nz]
        A "read-only" view of `_idx_coo`.
    n_batch_dim
        The number of batch dimensions (either one or zero).
    n_sp_dim
        The number of sparse dimensions (which is always two).
    T
        The matrix transpose on the two sparse dimensions.
    dtype
        The integer dtype of the `idx_coo` tensor.
    device
        The device of the `idx_coo` tensor.
    idx_crow : [*b, r+1]
        The CSR format compressed row index of the tensor (`crow_indices`).
    idx_col : [*b, nz_per_b]
        The CSR format col index of the tensor (`col_indices`).
    csc_to_coo_map : [nz,]
        The permutation that converts col-major to row-major index ordering.
    idx_ccol : [*b, c+1]
        The CSC format compressed col index of the tensor (`ccol_indices`).
    idx_row_csc : [*b, nz_per_b]
        The CSC format row index of the tensor (`row_indices`).

    Notes
    -----
    This class follows the following rules for integer tensor dtypes:

    * `idx_coo` must be int64 to conform to PyTorch Sparse COO tensor requirement.
    * `csc_to_coo_map` must be int64 for tensor indexing.
    * All other integer/index tensors are cast to int32 if it is safe to do so;
      otherwise they follow the same dtype as `idx_coo`.
    """

    _idx_coo: Int64[Tensor, "sp nz"]
    shape: tuple[int, ...] | torch.Size
    block_diag_config: BlockDiagConfig | None = None
    _coalesce_idx_map: Integer[Tensor, " nz"] | None = None

    @property
    def idx_coo(self) -> Int64[Tensor, "sp nz"]:
        """A "read-only" view of `_idx_coo`."""
        return self._idx_coo

    def __post_init__(self):
        _validate_coo_idx_shape(self.idx_coo, self.shape)

        # Manual out-of-bound index check
        if self.idx_coo.numel() > 0:
            min_idx = self.idx_coo.amin(dim=1)
            lower_ok = (min_idx >= 0).all()

            max_idx = self.idx_coo.amax(dim=1)
            bounds = torch.tensor(
                self.shape, device=self.idx_coo.device, dtype=self.idx_coo.dtype
            )
            upper_ok = (max_idx < bounds).all()

            if not (upper_ok and lower_ok):
                raise ValueError("idx_coo contains out-of-bound indices.")

        # Enforce dtype, ownership and contiguous memory layout. Use
        # object.__setattr__() to bypass frozen=True.
        object.__setattr__(
            self,
            "_idx_coo",
            self._idx_coo.detach().to(
                dtype=torch.int64, memory_format=torch.contiguous_format, copy=True
            ),
        )

        # Coerse shape dtype.
        object.__setattr__(self, "shape", torch.Size(self.shape))

        # Weakref cache for masked sparse-sparse matmul planning.
        object.__setattr__(self, "_spsp_matmul_plans", weakref.WeakKeyDictionary())

    @cached_property
    def _is_int32_safe(self) -> bool:
        """Check whether the sparsity pattern can be represented with int32 dtype."""
        int32_max = torch.iinfo(torch.int32).max

        nnz_is_safe = self._nnz() < int32_max
        n_row_is_safe = self.size(-2) < int32_max
        n_col_is_safe = self.size(-1) < int32_max

        return nnz_is_safe & n_row_is_safe & n_col_is_safe

    @classmethod
    def pack_block_diag(
        cls, block_patterns: Sequence[SparsityPattern]
    ) -> SparsityPattern:
        """Determine the sparsity pattern of a block-diagonal tensor."""
        # Pick a representative SparsityPattern and use it to determine device,
        # dtype, and batch/dense dimension information.
        rep_pattern = block_patterns[0]

        device = rep_pattern.device
        idx_dtype = rep_pattern.dtype

        # Determine the input SparsityPattern sparse row/column shapes.
        r_sizes_cum = torch.tensor(
            [0] + [pattern.size(-2) for pattern in block_patterns],
            dtype=idx_dtype,
            device=device,
        ).cumsum(dim=0)

        c_sizes_cum = torch.tensor(
            [0] + [sdt.size(-1) for sdt in block_patterns],
            dtype=idx_dtype,
            device=device,
        ).cumsum(dim=0)

        # Compute block offsets and apply to concatenated coo index.
        nnzs = [pattern._nnz() for pattern in block_patterns]
        nnz_concat = torch.tensor(nnzs, dtype=idx_dtype, device=device)

        r_offset = torch.repeat_interleave(r_sizes_cum[:-1], nnz_concat)
        c_offset = torch.repeat_interleave(c_sizes_cum[:-1], nnz_concat)

        idx_coo_concat = torch.hstack(
            [
                pattern.idx_coo.to(device=device, dtype=idx_dtype)
                for pattern in block_patterns
            ]
        )
        idx_coo_concat[-2] += r_offset
        idx_coo_concat[-1] += c_offset

        # If there is a batch dimension, the coo index needs to be sorted first
        # by batch item order; find the permutation for this sort. If there is no
        # batch dim, this sort does nothing.
        batch_perm = torch.argsort(idx_coo_concat[0], stable=True)

        # Determine the concatenated SparsityPattern shape.
        if rep_pattern.n_batch_dim > 0:
            pattern_shape_concat = torch.Size(
                [rep_pattern.size(0), r_sizes_cum[-1], c_sizes_cum[-1]]
            )
        else:
            pattern_shape_concat = torch.Size([r_sizes_cum[-1], c_sizes_cum[-1]])

        # Record block diag construction information for disassembly
        # block_ptr = torch.repeat_interleave(torch.arange(len(sp_ops)), nnz_concat)
        pattern_shapes = [pattern.shape for pattern in block_patterns]
        config = BlockDiagConfig(batch_perm, nnzs, pattern_shapes)

        # Construct concatenated SparsityPattern.
        pattern_concat = SparsityPattern(
            idx_coo_concat[:, batch_perm],
            shape=pattern_shape_concat,
            block_diag_config=config,
        )

        return pattern_concat

    def unpack_block_diag(
        self,
    ) -> tuple[list[SparsityPattern], Int64[Tensor, " nz"]]:
        """Deconstruct a block-diagonal `SparsityPattern` into its constituents."""
        if not isinstance(self.block_diag_config, BlockDiagConfig):
            raise ValueError("A valid 'block_diag_config' is required for disassembly.")

        device = self.device
        idx_dtype = self.dtype

        # Undo the batch dim sort, so that the idx_coo is back in a per-block
        # ordering. Fancy indexing guarantees copying.
        block_perm_inv = self.block_diag_config.batch_perm_inv
        idx_coo_concat = self.idx_coo[:, block_perm_inv]

        # Undo the per-block, cumulative index offsets.
        r_sizes_cum = torch.tensor(
            [0] + [shape[-2] for shape in self.block_diag_config.pattern_shapes],
            dtype=idx_dtype,
            device=device,
        ).cumsum(dim=0)

        c_sizes_cum = torch.tensor(
            [0] + [shape[-1] for shape in self.block_diag_config.pattern_shapes],
            dtype=idx_dtype,
            device=device,
        ).cumsum(dim=0)

        nnz_concat = torch.tensor(
            self.block_diag_config.nnzs, dtype=idx_dtype, device=device
        )

        r_offset = torch.repeat_interleave(r_sizes_cum[:-1], nnz_concat)
        c_offset = torch.repeat_interleave(c_sizes_cum[:-1], nnz_concat)

        idx_coo_concat[-2] -= r_offset
        idx_coo_concat[-1] -= c_offset

        # Split the concatenated idx_coo into constituent parts. Note that
        # torch.split() creates a view without copying; this is okay because the
        # SparsityPattern constructor enforces copying.
        idx_coo_list = torch.split(idx_coo_concat, self.block_diag_config.nnzs, dim=-1)

        pattern_list = [
            SparsityPattern(idx_coo, shape)
            for idx_coo, shape in zip(
                idx_coo_list, self.block_diag_config.pattern_shapes, strict=True
            )
        ]

        return pattern_list, block_perm_inv

    # TODO: optimize to avoid multiple index tensor copies
    @classmethod
    def bmat(
        cls, patterns: Sequence[Sequence[SparsityPattern | None]]
    ) -> tuple[SparsityPattern, Int64[Tensor, " nz"]]:
        """
        Determine the `SparsityPattern` of a block matrix.

        Determine how to combine a 2D grid of `SparsityPattern`s to construct a
        block matrix operator. `None` is allowed to represent empty/zero blocks. Note
        that rows/columns with all `None` or degenerate blocks are allowed.
        """
        # Pick a representative SparsityPattern and use it to determine device,
        # dtype, and batch/dense dimension information.
        rep_pattern = None
        for pattern_row in patterns:
            for pattern in pattern_row:
                if pattern is not None:
                    rep_pattern = pattern

        if rep_pattern is None:
            raise ValueError("At least one block in 'blocks' must be non-null value.")

        device = rep_pattern.device
        idx_dtype = rep_pattern.dtype

        # Determine the input SparsityPattern sparse row/column shapes. The row
        # sizes and col sizes are each represented as a 2D tensor; None is assigned
        # a shape of -1.
        r_sizes = []
        c_sizes = []
        for pattern_row in patterns:
            row_r_sizes = []
            row_c_sizes = []

            for pattern in pattern_row:
                if pattern is None:
                    row_r_sizes.append(-1)
                    row_c_sizes.append(-1)
                else:
                    row_r_sizes.append(pattern.size(-2))
                    row_c_sizes.append(pattern.size(-1))

            r_sizes.append(row_r_sizes)
            c_sizes.append(row_c_sizes)

        r_sizes = torch.tensor(r_sizes, dtype=idx_dtype, device=device)
        c_sizes = torch.tensor(c_sizes, dtype=idx_dtype, device=device)

        # Sanity checks on the row/col shape tensors: the r_sizes tensor should
        # have constant rows, and the c_sizes tensor should have constant cols,
        # with the exception being None is allowed with a -1 value.
        for sp_op_dims, check_dim in zip([r_sizes, c_sizes], [1, 0]):
            eq_to_max = sp_op_dims == sp_op_dims.max(dim=check_dim, keepdim=True).values
            eq_to_null = sp_op_dims == -1

            if not (eq_to_max | eq_to_null).all():
                raise ValueError(
                    "Block dimensions must match along their respective rows and columns."
                )

        # Clamp the -1 values introduced by None to 0 and determine the (physical)
        # row and col block sizes.
        r_sizes_clamped = torch.clamp_min(r_sizes.max(dim=1).values, 0)
        c_sizes_clamped = torch.clamp_min(c_sizes.max(dim=0).values, 0)

        # Construct the concatenated coo index by iterating over the block coo indices.
        idx_coo_list = []
        r_offset = torch.tensor(0, dtype=idx_dtype, device=device)
        c_offset = torch.tensor(0, dtype=idx_dtype, device=device)
        for r_idx, pattern_row in enumerate(patterns):
            for c_idx, pattern in enumerate(pattern_row):
                if pattern is not None:
                    idx_coo = (
                        pattern.idx_coo.detach()
                        .clone()
                        .to(device=device, dtype=idx_dtype)
                    )
                    idx_coo[-2] += r_offset
                    idx_coo[-1] += c_offset
                    idx_coo_list.append(idx_coo)

                c_offset += c_sizes_clamped[c_idx]

            r_offset += r_sizes_clamped[r_idx]
            c_offset = 0

        idx_coo_concat = torch.hstack(idx_coo_list)

        # If there is a batch dimension, the coo index needs to be sorted first
        # by batch item order; find the permutation for this sort.
        batch_perm = torch.sort(idx_coo_concat[0], stable=True).indices

        # Determine the concatenated SparsityPattern shape.
        n_row = r_sizes_clamped.sum().item()
        n_col = c_sizes_clamped.sum().item()
        if rep_pattern.n_batch_dim > 0:
            pattern_shape_concat = torch.Size([rep_pattern.size(0), n_row, n_col])
        else:
            pattern_shape_concat = torch.Size([n_row, n_col])

        # Construct concatenated coo index.
        pattern_concat = SparsityPattern(
            idx_coo_concat[:, batch_perm], shape=pattern_shape_concat
        )

        return pattern_concat, batch_perm

    def submatrix(
        self, row_mask: Bool[Tensor, " r"], col_mask: Bool[Tensor, " c"] | None = None
    ) -> tuple[Bool[Tensor, " nz"], SparsityPattern]:
        """
        Determine the `SparsityPattern` of a submatrix using row and col masks.

        This method preserves and updates BlockDiagConfig, if there is any.
        """
        r_idx = self.idx_coo[-2]
        c_idx = self.idx_coo[-1]

        if col_mask is None:
            col_mask = row_mask

        # Determine the submatrix nonzero elements mask.
        r_idx_submat_mask = row_mask[r_idx]
        c_idx_submat_mask = col_mask[c_idx]

        # Only nonzero elements that are covered by both the row and col masks
        # are preserved.
        idx_coo_submat_mask = r_idx_submat_mask & c_idx_submat_mask

        # Determine the size of the submatrix.
        r_submat_size = row_mask.sum().item()
        c_submat_size = col_mask.sum().item()

        if self.n_batch_dim > 0:
            submat_shape = torch.Size([self.size(0), r_submat_size, c_submat_size])
        else:
            submat_shape = torch.Size([r_submat_size, c_submat_size])

        # Adjust the COO index to account for subsetting.

        # The cumsum() on the index mask maps the old indices to new indices.
        # For example, let idx = [0, 1, 3, 4] and mask = [T, F, F, T, T].
        # Then idx_map = [0, 0, 0, 1, 2] and
        #
        #    mask[idx] = [T, F, T, T]             # mask for subsetting the idx
        #    idx[mask[idx]] = [0, 3, 4]           # subsetted idx
        #    idx_map[idx[mask[idx]]] = [0, 1, 2]  # map to renumbered idx
        #
        # This gives the correct subsetting and renumbering of the original idx.
        r_idx_map = torch.cumsum(row_mask, dim=0) - 1
        c_idx_map = torch.cumsum(col_mask, dim=0) - 1

        idx_coo_row_submat = r_idx_map[r_idx[idx_coo_submat_mask]]
        idx_coo_col_submat = c_idx_map[c_idx[idx_coo_submat_mask]]

        # Adjust the block_diag_config, if there is any.
        if self.block_diag_config is None:
            submat_block_diag_config = None

        else:
            # Update pattern_shapes.

            # Split the row_mask and col_mask into its block components.
            r_idx_submat_block_masks = torch.split(
                row_mask, [s[-2] for s in self.block_diag_config.pattern_shapes]
            )
            c_idx_submat_block_masks = torch.split(
                col_mask, [s[-1] for s in self.block_diag_config.pattern_shapes]
            )

            # For each block, sum the per-block row/col mask to get the subset shape.
            submat_pattern_sizes = []
            for block_shape_original, block_r_idx_mask, block_c_idx_mask in zip(
                self.block_diag_config.pattern_shapes,
                r_idx_submat_block_masks,
                c_idx_submat_block_masks,
                strict=True,
            ):
                if self.n_batch_dim > 0:
                    submat_pattern_sizes.append(
                        torch.Size(
                            [
                                block_shape_original[0],
                                block_r_idx_mask.sum().item(),
                                block_c_idx_mask.sum().item(),
                            ]
                        )
                    )
                else:
                    submat_pattern_sizes.append(
                        torch.Size(
                            [
                                block_r_idx_mask.sum().item(),
                                block_c_idx_mask.sum().item(),
                            ]
                        )
                    )

            # Update nnzs.
            block_perm_inv = self.block_diag_config.batch_perm_inv

            # Undo the batch dim sort on idx_coo_submat_mask to put it in a
            # per-block odering.
            idx_coo_submat_mask_block_concat = idx_coo_submat_mask[block_perm_inv]
            # Split the block-ordered idx_coo_submat_mask into its block components.
            idx_coo_submat_block_masks = torch.split(
                idx_coo_submat_mask_block_concat, self.block_diag_config.nnzs
            )
            # Sum the per-block idx_coo_submat_mask to get per-block nnzs.
            submat_block_nnzs = [
                mask.sum().item() for mask in idx_coo_submat_block_masks
            ]

            # Update batch_perm.
            # The batch_perm index tensor can be subsetted and renumbered the
            # same way as the idx_coo tensor using the cumsum() method. However,
            # since the indices in batch_perm refer to elements in the per-block
            # ordering, the cumsum() needs to be applied to the the mask in the
            # same per-block ordering (idx_coo_submat_mask_block_concat) rather
            # than the per-batch element ordering (idx_coo_submat_mask).
            batch_perm_idx_map = (
                torch.cumsum(idx_coo_submat_mask_block_concat, dim=0) - 1
            )
            # Note that, to subset the batch_perm, we use the per-batch element
            # ordered mask (idx_coo_submat_mask) rather than the per-block ordered
            # mask (idx_coo_submat_mask_block_concat), because, even though the
            # indices in batch_perm refer to elements in the per-block ordering,
            # the position of these indices in batch_perm is in the per-batch
            # element order.
            submat_batch_perm = batch_perm_idx_map[
                self.block_diag_config.batch_perm[idx_coo_submat_mask]
            ]

            # Construct new BlockDiagConfig for the submatrix.
            submat_block_diag_config = BlockDiagConfig(
                batch_perm=submat_batch_perm,
                nnzs=submat_block_nnzs,
                pattern_shapes=submat_pattern_sizes,
            )

        # Construct the new submatrix SparsityPattern.
        if self.n_batch_dim > 0:
            idx_coo_batch_submat = self.idx_coo[0][idx_coo_submat_mask]
            submat_idx_coo = torch.stack(
                (idx_coo_batch_submat, idx_coo_row_submat, idx_coo_col_submat)
            )
        else:
            submat_idx_coo = torch.stack((idx_coo_row_submat, idx_coo_col_submat))

        submat_pattern = SparsityPattern(
            submat_idx_coo,
            shape=submat_shape,
            block_diag_config=submat_block_diag_config,
        )

        return idx_coo_submat_mask, submat_pattern

    def size(self, dim: int | None = None) -> int | torch.Size:
        """Return the shape of the sparse tensor."""
        if dim is None:
            return self.shape
        else:
            return self.shape[dim]

    def _nnz(self) -> int:
        """
        Return the total number of nonzero/specified elements in the sparse tensor.

        In PyTorch, for batched sparse CSC/CSR tensors, the _nnz() method returns
        the number of nonzero elements per batch item; for sparse COO tensors,
        the _nnz() method returns the total number of nonzero elements, regardless
        of batch dimensions. Here we follow the sparse COO convention.
        """
        return self.idx_coo.size(1)

    @property
    def n_batch_dim(self) -> int:
        """The number of batch dimensions (either one or zero)."""
        return self.idx_coo.size(0) - 2

    @property
    def n_sp_dim(self) -> int:
        """
        The number of sparse dimensions (which is always two).

        In Pytorch, for sparse CSC/CSR tensors, the leading batch dimension(s) do
        not count towards `sparse_dim()`; for sparse COO tensors, no such distinction
        is made. Here we follow the sparse CSC/CSR convention.
        """
        return 2

    # TODO: investigate interaction with block_diag_config and coalesce_idx_map.
    @property
    def T(self) -> SparsityPattern:
        """
        The matrix transpose along the two sparse dimensions.

        Note that this operation preserves the cache of existing sparse index
        tensors via cache injection.
        """
        idx_coo_sorted = self.idx_coo[:, self.csc_to_coo_map]

        idx_coo_trans = idx_coo_sorted.clone()
        idx_coo_trans[-1] = idx_coo_sorted[-2]
        idx_coo_trans[-2] = idx_coo_sorted[-1]

        shape_trans = self.shape[:-2] + (self.shape[-1], self.shape[-2])

        pattern_trans = SparsityPattern(idx_coo_trans, shape_trans)

        attr_map = {
            "idx_ccol": "idx_crow",
            "idx_crow": "idx_ccol",
            "idx_col": "idx_row_csc",
            "idx_row_csc": "idx_col",
        }

        for attr, attr_trans in attr_map.items():
            if attr in self.__dict__:
                pattern_trans.__dict__[attr_trans] = self.__dict__[attr]

        return pattern_trans

    @property
    def dtype(self) -> torch.dtype:
        """The integer dtype of the `idx_coo` tensor."""
        return self.idx_coo.dtype

    @property
    def device(self) -> torch.device:
        """The device of the `idx_coo` tensor."""
        return self.idx_coo.device

    def to(self, *args, **kwargs) -> SparsityPattern:
        """
        Perform dtype and/or device conversion.

        This function accept some PyTorch `to()` arguments and apply them to all
        tensor attributes attached to the `SparsityPattern` (including any cached
        index tensors) and its `BlockDiagConfig`. In particular, the index tensors
        associated with self ignore dtype conversions and `memory_format`, while
        tensors associated with `BlockDiagConfig` ignores dtype conversion only.
        """
        # Parse input arguments.
        device, dtype, copy_flag, non_blocking, memory_format = parse_to(
            *args, **kwargs
        )

        new_idx_coo = self.idx_coo.to(
            device=device, copy=copy_flag, non_blocking=non_blocking
        )

        if self._coalesce_idx_map is None:
            new_coalesce_idx_map = None
        else:
            new_coalesce_idx_map = self._coalesce_idx_map.to(
                device=device, copy=copy_flag, non_blocking=non_blocking
            )

        # block_diag_config handles its own to() call.
        if self.block_diag_config is None:
            new_block_diag_config = None
        else:
            new_block_diag_config = self.block_diag_config.to(*args, **kwargs)

        new_pattern = SparsityPattern(
            new_idx_coo, self.shape, new_block_diag_config, new_coalesce_idx_map
        )

        # Handle the cached index tensors.
        cached_idx_tensors = [
            "csc_to_coo_map",
            "idx_ccol",
            "idx_crow",
            "idx_col",
            "idx_row_csc",
        ]

        for attr in cached_idx_tensors:
            if attr in self.__dict__:
                new_pattern.__dict__[attr] = self.__dict__[attr].to(
                    device=device, copy=copy_flag, non_blocking=non_blocking
                )

        return new_pattern

    @cached_property
    def idx_crow(self) -> Integer[Tensor, "*b r+1"]:
        """
        The CSR format compressed row index of the tensor (`crow_indices`).

        this property is cached once computed. This tensor will be cast to `int32`
        dtype if it is safe to do so; otherwise it has the same dtype as `idx_coo`.
        """
        return coalesced_coo_to_compressed_idx(
            self.idx_coo,
            self.shape,
            format="crow",
            dtype=torch.int32 if self._is_int32_safe else self.dtype,
        )

    @cached_property
    def idx_col(self) -> Integer[Tensor, "*b nz_per_b"]:
        """
        The CSR format col index of the tensor (`col_indices`).

        This property is cached once computed. This tensor will be cast to `int32`
        dtype if it is safe to do so; otherwise it has the same dtype as `idx_coo`.

        If the tensor has no batch dimension, then `idx_col` is identical to
        `idx_coo[-1]`; if there is a batch dimension, then `idx_col` differs from
        `idx_coo[-1]` in that it has an explicit batch dimension.
        """
        return coalesced_coo_to_csr_col_idx(
            self.idx_coo,
            self.shape,
            dtype=torch.int32 if self._is_int32_safe else self.dtype,
        )

    @cached_property
    def csc_to_coo_map(self) -> Int64[Tensor, " nz"]:
        """
        The permutation that converts row-major to col-major index ordering.

        Specifically, this function computes the function `map[i]=j` that maps
        the index of the `i`th nonzero element in the COO/CSR ordering to its
        index `j` in the CSC odering; therefore, `values[map]` converts the
        values tensor from the COO/CSR ordering to the CSC ordering.

        This property is cached once computed. Unlike other index tensors,
        this tensor always has an `int64` dtype.
        """
        return get_csc_to_coo_map(self.idx_coo, self.shape)

    @cached_property
    def idx_ccol(self) -> Integer[Tensor, "*b c+1"]:
        """
        The CSC format compressed col index of the tensor (`ccol_indices`).

        this property is cached once computed. This tensor will be cast to `int32`
        dtype if it is safe to do so; otherwise it has the same dtype as `idx_coo`.
        """
        return coalesced_coo_to_compressed_idx(
            self.idx_coo,
            self.shape,
            format="ccol",
            dtype=torch.int32 if self._is_int32_safe else self.dtype,
        )

    @cached_property
    def idx_row_csc(self) -> Integer[Tensor, "*b nz_per_b"]:
        """
        The CSC format row index of the tensor (`row_indices`).

        This property is cached once computed. This tensor will be cast to `int32`
        dtype if it is safe to do so; otherwise it has the same dtype as `idx_coo`.

        Note that this tensor is different from `idx_coo[-2]` because the indices
        in the CSC format are sorted in col-major order.
        """
        return coalesced_coo_to_csc_row_idx(
            self.idx_coo,
            self.shape,
            self.csc_to_coo_map,
            dtype=torch.int32 if self._is_int32_safe else self.dtype,
        )
